### ISSUE TITLE
Homepage - Video custom post featured image not implemented. 

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Dr-Andrew-Dean#105]
![image](https://cloud.githubusercontent.com/assets/12791909/10778907/64a41ed2-7d65-11e5-83b4-9ad4b2c6a42c.png)

**Comment by ravititan** [comment]
Could you please explain more ?

**Comment by ermatitan** [comment]
Hello Ravi, 

What I mean is, wp should generate a thumbnail image based on the content of the video not the plain gray background. Please check You Tube functionality in displaying its video thumbnails. 

See web design: 
![image](https://cloud.githubusercontent.com/assets/12791909/10988459/4dbe0700-8477-11e5-8972-e4b818df444c.png)
