### ISSUE TITLE
Homepage-Gmap (Pre-footer section): Google maps customized marker not implemented.

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/Dr-Andrew-Dean#12]
![6](https://cloud.githubusercontent.com/assets/13309806/10038576/6912cd04-6174-11e5-8450-2f65d3f3fd16.png)

**Comment by ravititan** [comment]
client need to provide key

**Comment by mahender-sowedane** [comment]
As per design should be implement customized marker.

![wamo-bug](https://cloud.githubusercontent.com/assets/13309730/10410282/97851d56-6f5a-11e5-9ddb-8344ba5a3c74.png)
