### ISSUE TITLE
Contact us field label font weight should set to normal/400 since font family is already bold.

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Dr-Andrew-Dean#160]
![image](https://cloud.githubusercontent.com/assets/12791909/10988819/dc42c562-847a-11e5-9332-485320e70445.png)

**Comment by ermatitan** [comment]
I have cleared my cache, and problem still not fix.

**Comment by ravititan** [comment]
![wamo-contact-label](https://cloud.githubusercontent.com/assets/13450891/11471222/d3303884-9789-11e5-9028-c68181fce6f6.jpg)
Please check the screenshot.
