### ISSUE TITLE
Inner banner: Inner banner title is not displaying

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/Dr-Andrew-Dean#18]
Devices : Ipad, Ipad(mini), Ipod, Samsung E7

![all-2](https://cloud.githubusercontent.com/assets/13309806/10039974/bb680c72-6183-11e5-9a55-66c1de75f660.png)

**Comment by ravi-josyula** [comment]
Still bug is not fixed in Itouch

**Comment by ravititan** [comment]
I have tested on itouch and it is working fine.
