### ISSUE TITLE
Homepage - Why Wamo - Listing image (+) size is smaller than the design

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Dr-Andrew-Dean#184]
![image](https://cloud.githubusercontent.com/assets/12791909/11387710/6c6803cc-9368-11e5-9a0a-d759fc2dc73f.png)

**Comment by ravititan** [comment]
The + image size is 57px same as design.
![wamo-list-psd](https://cloud.githubusercontent.com/assets/13450891/11470661/9765baee-9785-11e5-8e1b-a9c74aed27cf.jpg)
![wamo-list](https://cloud.githubusercontent.com/assets/13450891/11470662/97661fb6-9785-11e5-81b5-4785af807f8e.jpg)
