### ISSUE TITLE
Home page(Welcome to WAMO section): "Read more/Hide" button is not working properly in Ipad and Ipad(mini)

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/Dr-Andrew-Dean#26]
![ipad mini6](https://cloud.githubusercontent.com/assets/13309806/10040392/a2738d00-6187-11e5-89df-746460d73135.png)

**Comment by ravi-josyula** [comment]
Still bug is not fixed

**Comment by ravititan** [comment]
I have checked on Ipad and Ipod and it works fine.
