### ISSUE TITLE
Contact Us page :Gmap pointer should be implemented as per design

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/Dr-Andrew-Dean#48]
![1](https://cloud.githubusercontent.com/assets/13309806/10043160/2dbab824-619d-11e5-9e8d-0e0f4e2b2761.png)

**Comment by ravititan** [comment]
awaiting key to customize it

**Comment by ravi-josyula** [comment]
Will you please explain what is key?

![2015-10-12_1031](https://cloud.githubusercontent.com/assets/13309806/10421742/aa378302-705a-11e5-8652-a6f622b39d5e.png)
