### ISSUE TITLE
Admin : There is no set featured image in admin panel, still displaying in frontend

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/Dr-Andrew-Dean#56]
![4](https://cloud.githubusercontent.com/assets/13309806/10068910/ebab7bea-6254-11e5-8a56-6cbbbac9cfd4.png)

**Comment by ravititan** [comment]
Need to discuss, It is not possible through featured image as the leadin images have the hover effect.

**Comment by ravi-josyula** [comment]
But 'hover effect' is not mentioned in scope, have a look below screen. please confirm with your TL and let me know.

![2015-10-08_1303](https://cloud.githubusercontent.com/assets/13309806/10360176/3e52c1b8-6d4b-11e5-9407-bbfbba89ae3b.png)

**Comment by ravi-josyula** [comment]
As per the scope featured image should be used otherwise 'hover effect' ACF field need to implement.
here there is no options but still lead-in's icons are displaying.
And also need to implement all lead-ins icons as per design, have a look this screenshots
thanks!

![untitled-1](https://cloud.githubusercontent.com/assets/13309806/10538405/b2f36fa4-73a4-11e5-830c-ea755e3394d1.jpg)

![untitled-2](https://cloud.githubusercontent.com/assets/13309806/10538474/18c364c4-73a5-11e5-9ad2-74bce31c0f94.gif)
