### ISSUE TITLE
News feed section : News feeds are not reflecting to their respective pages

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/Dr-Andrew-Dean#60]
![8](https://cloud.githubusercontent.com/assets/13309806/10069102/4fe3f8de-6256-11e5-9a2e-caad722ffa95.png)

**Comment by ravititan** [comment]
go to admin... give pagelink

**Comment by ravi-josyula** [comment]
I am aware of that but while testing i found this issue, now its fixed.
