### ISSUE TITLE
Admin : All posts are not displaying

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/Dr-Andrew-Dean#75]
![all-posts-are-not-displaying](https://cloud.githubusercontent.com/assets/13309806/10070241/b10e2592-625d-11e5-8b13-b62745cd10e1.png)

**Comment by ravititan** [comment]
only 8 will display on home

**Comment by ravi-josyula** [comment]
As per the scope there is no limit for services, have a look on screen shot
![serv](https://cloud.githubusercontent.com/assets/13309806/10360352/8ba348ce-6d4c-11e5-9efc-1105b03535e2.png)
